#pragma once

#include "root_component.h"
#include "parent_component.h"
#include "children_component.h"
#include "name_component.h"
#include "transform_component.h"
#include "mesh_component.h"
#include "mesh_info_component.h"
#include "shader_component.h"
#include "shader_info_component.h"
#include "point_light_component.h"
#include "camera_component.h"
#include "script_component.h"
#include "script_info_component.h"
#include "material_component.h"